# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm # or mongodb or phpcr
  mappings:
    property_image:
      uri_prefix: /images/properties
      upload_destination: "%kernel.project_dir%/public/images/properties"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
